#!/usr/bin/env python3
import sys


def solve(N: int, A: int, B: int):
    # B-A-1からN-2個選ぶ
    # 和は重複する可能性あり
    if N == 1:
        if A == B:
            print(1)
            return
        else:
            print(0)
            return
    elif N == 2:
        print(1)
        return

    if A > B:
        print(0)
        return

    ans = (B - A) * (N - 2) + 1
    print(ans)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(N, A, B)

if __name__ == '__main__':
    main()
