#!/usr/bin/env python3
import sys
import math


def solve(X: int):
    while True:
        prime = True
        for i in range(2, math.floor(X / 2)):
            if X % i == 0:
                prime = False
                break
        if prime:
            print(X)
            return
        X += 1
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    X = int(next(tokens))  # type: int
    solve(X)

if __name__ == '__main__':
    main()
