#include <bits/stdc++.h>
using namespace std;

const long long MOD = 1000000007;

void solve(std::vector<long long> X, std::vector<long long> Y){

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    std::vector<long long> X(6);
    for(int i = 0 ; i < 6 ; i++){
        scanf("%lld",&X[i]);
    }
    std::vector<long long> Y(6);
    for(int i = 0 ; i < 6 ; i++){
        scanf("%lld",&Y[i]);
    }
    solve(std::move(X), std::move(Y));
    return 0;
}
