#!/usr/bin/env python3
import sys


def solve(N: int, S: str):
    ans = 0
    for i in range(1, N-1):
        tmp_ans = 0
        first = S[:i]
        last = S[i:]
        first_chars = set()
        last_chars = set()
        for s in first:
            first_chars.add(s)
        for s in last:
            last_chars.add(s)
        for c in first_chars:
            if c in last_chars:
                tmp_ans += 1
        if tmp_ans > ans:
            ans = tmp_ans
    print(ans)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    S = next(tokens)  # type: str
    solve(N, S)

if __name__ == '__main__':
    main()
