#!/usr/bin/env python3
import sys
import math


def solve(N: int, a: "List[int]"):
    ans = set()
    red = 0
    for i in a:
        if i >= 3200:
            red += 1
        else:
            ans.add(math.floor(i / 400))
    print(max(len(ans), min(1, red)), len(ans) + red)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, a)

if __name__ == '__main__':
    main()
