#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(c: "List[List[int]]"):
    cases = [(0, 1), (1, 2), (2, 0)]
    for case in cases:
        tmp = (c[0][case[0]] - c[0][case[1]])
        for i in range(1, 3):
            if not tmp == (c[i][case[0]] - c[i][case[1]]):
                print(NO)
                return
    for case in cases:
        tmp = (c[case[0]][0] - c[case[1]][0])
        for i in range(1, 3):
            if not tmp == (c[case[0]][i] - c[case[1]][i]):
                print(NO)
                return
    print(YES)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    c = [[int(next(tokens)) for _ in range(3)] for _ in range(3)]  # type: "List[List[int]]"
    solve(c)

if __name__ == '__main__':
    main()
