#include <bits/stdc++.h>
using namespace std;
using ll = long long;

void solve(long long N, long long A, long long B){
  ll nokori = N % (A + B);
  ll loop = N / (A + B);
  ll ans = loop * A + min(nokori, A);
  cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long A;
    scanf("%lld",&A);
    long long B;
    scanf("%lld",&B);
    solve(N, A, B);
    return 0;
}
