#!/usr/bin/env python3
import sys


def solve(W: int, H: int, p: "List[int]", q: "List[int]"):
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    W = int(next(tokens))  # type: int
    H = int(next(tokens))  # type: int
    p = [int(next(tokens)) for _ in range(W - 1 - 0 + 1)]  # type: "List[int]"
    q = [int(next(tokens)) for _ in range(H - 1 - 0 + 1)]  # type: "List[int]"
    solve(W, H, p, q)

if __name__ == '__main__':
    main()
