#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> A){
  long long ans = 0;
  long long tmp = 0;
  sort(A.begin(), A.end());
  for (int i = 0; i < N - 1; i++) {
    //cout << A[i] << endl;
    tmp += A[i];
    if (tmp * 2 < A[i + 1]) {
      // 合体できない
      ans = 0;
    } else {
      ans ++;
    }
  }
  ans ++;
  cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
