#!/usr/bin/env python3
import sys
import math


def solve(N: int, X: "List[int]"):
    sum = math.inf
    X.sort()
    for i in range(X[0], X[-1]+1):
        tmp_sum = 0
        for j in range(len(X)):
            tmp_sum += (X[j] - i) ** 2
        if tmp_sum < sum:
            sum = tmp_sum
    print(sum)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    X = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, X)

if __name__ == '__main__':
    main()
