#!/usr/bin/env python3
import sys


def solve(N: int, M: int, X: int, A: "List[int]"):
    to_n = 0
    to_0 = 0
    for a in A:
        if a > X:
            to_n += 1
        else:
            to_0 += 1

    print(min(to_n, to_0))
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    M = int(next(tokens))  # type: int
    X = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(M)]  # type: "List[int]"
    solve(N, M, X, A)

if __name__ == '__main__':
    main()
