#!/usr/bin/env python3
import sys


def solve(N: int):
    if N % 2 != 0:
        print(0)
        return
    cnt5 = 0
    i = 2
    while True:
        i *= 5
        tmp_cnt5 = N // i
        cnt5 += tmp_cnt5
        if tmp_cnt5 == 0:
            break
    print(cnt5)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    solve(N)

if __name__ == '__main__':
    main()
