#!/usr/bin/env python3
import sys


def solve(N: int, T: int, t: "List[int]"):
    ans = T
    last = 0
    for l in t:
        if l < last + T: #重なりあり
            ans += T - (last + T - l)
        else:
            ans += T
        last = l
    print(ans)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    T = int(next(tokens))  # type: int
    t = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, T, t)

if __name__ == '__main__':
    main()
