#!/usr/bin/env python3
import sys

YES = "YES"  # type: str
NO = "NO"  # type: str


def solve(S: str):
    while len(S) > 0:
        #print(S)
        #print(S[-6:])
        if len(S) > 4 and S[-5:] in ["dream", "erase"]:
            S = S[:-5]
        elif len(S) > 5 and S[-6:] == "eraser":
            S = S[:-6]
        elif len(S) > 6 and S[-7:] == "dreamer":
            S = S[:-7]
        else:
            print(NO)
            return
    print(YES)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
