#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(S: str, T: str):
    h = {}
    l = {}
    for s, t in zip(S, T):
        #print(h)
        if s in h:
            if h[s] != t:
                #print(s, h[s], t)
                print(NO)
                return
        if t in l:
            if l[t] != s:
                #print(t, l[t], s)
                print(NO)
                return
        else:
            h[s] = t
            l[t] = s
    print(YES)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    T = next(tokens)  # type: str
    solve(S, T)

if __name__ == '__main__':
    main()
