#!/usr/bin/env python3
import sys


def solve(S: str):
    order = [0] * (len(S) + 1)
    for idx in range(len(S)):
        if S[idx] == '<':
            order[idx + 1] = order[idx] + 1
    for idx in reversed(range(len(S))):
        if S[idx] == '>' and order[idx] < order[idx + 1] + 1:
            order[idx] = order[idx + 1] + 1
    ans = sum(order)
    print(ans)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
