#!/usr/bin/env python3
import sys


def solve(N: int, a: "List[int]", b: "List[int]"):
    a_max = a[0]
    b_max = b[0] # 暫定解のb
    ab_max = a[0] * b[0]
    for i in range(N):
        if a[i] > a_max:
            a_max = a[i]
        if a_max * b[i] > ab_max:
            ab_max = a_max * b[i]
        print(ab_max)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    b = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, a, b)

if __name__ == '__main__':
    main()
