#!/usr/bin/env python3
import sys


def solve(s: int):
    prev = {s: True}
    i = 1
    while True:
        i += 1
        if s % 2 == 0:
            s /= 2
        else:
            s = 3 * s + 1

        if s in prev:
            print(i)
            break
        prev[s] = True
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    s = int(next(tokens))  # type: int
    solve(s)

if __name__ == '__main__':
    main()
