#include <bits/stdc++.h>
using namespace std;


void solve(long long N, std::vector<long long> T, long long M, std::vector<long long> P, std::vector<long long> X){

}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> T(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&T[i]);
    }
    long long M;
    scanf("%lld",&M);
    std::vector<long long> P(M);
    std::vector<long long> X(M);
    for(int i = 0 ; i < M ; i++){
        scanf("%lld",&P[i]);
        scanf("%lld",&X[i]);
    }
    solve(N, std::move(T), M, std::move(P), std::move(X));
    return 0;
}
