#!/usr/bin/env python3
import sys


def solve(N: int, A: "List[int]"):
    if N == 1:
        print(1)
        return

    ans = 1
    inc = None
    for i in range(1, N):
        if inc is None:
            inc = (A[i - 1] < A[i]) if A[i - 1] != A[i] else None # 等しいときもある
            continue
        if inc and A[i - 1] > A[i]:
            ans += 1
            inc = None
        elif (not inc) and A[i - 1] < A[i]:
            ans += 1
            inc = None
    print(ans)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
