#!/usr/bin/env python3
import sys


def solve(S: str):
    for i in range(1, int(len(S) / 2)): # 2こずつ消してく
        # [:(s + 2) / 2 - 1]と[(s + 2) / 2:]
        s = len(S) - 2 * i
        first = S[:int((s + 1) / 2)]
        last = S[int((s + 1) / 2):s]
        #print(first, last)
        if first == last:
            print(s)
            return
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    S = next(tokens)  # type: str
    solve(S)

if __name__ == '__main__':
    main()
