#!/usr/bin/env python3
import sys


def solve(N: int, s: str, t: str):
    for i in range(N):
        #print(s[i:])
        #print(t[:N - i])
        if s[i:] == t[:N - i]:
            print(N + i)
            return
    print(2 * N)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    s = next(tokens)  # type: str
    t = next(tokens)  # type: str
    solve(N, s, t)

if __name__ == '__main__':
    main()
