#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(H: int, W: int, s: "List[str]"):
    for i in range(H):
        for j in range(W):
            if s[i][j] == '#':
                if i > 0 and s[i - 1][j] == '#':
                    continue
                elif j > 0 and s[i][j - 1] == '#':
                    continue
                elif i < H - 1 and s[i + 1][j] == '#':
                    continue
                elif j < W - 1 and s[i][j + 1] == '#':
                    continue
                print(NO)
                return
    print(YES)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    s = [next(tokens) for _ in range(H)]  # type: "List[str]"
    solve(H, W, s)

if __name__ == '__main__':
    main()
