#!/usr/bin/env python3
import sys


def solve(sx: int, sy: int, tx: int, ty: int):
    X = tx - sx
    Y = ty - sy
    ans = 'R' * X + 'U' * Y + 'L' * X + 'D' * Y \
        + 'D' + 'R' * (X + 1) + 'U' * (Y + 1) + 'L' \
        + 'U' + 'L' * (X + 1) + 'D' * (Y + 1) + 'R'
    print(ans)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    sx = int(next(tokens))  # type: int
    sy = int(next(tokens))  # type: int
    tx = int(next(tokens))  # type: int
    ty = int(next(tokens))  # type: int
    solve(sx, sy, tx, ty)

if __name__ == '__main__':
    main()
