#!/usr/bin/env python3
import sys


def solve(N: int, C: "List[int]", S: "List[int]", F: "List[int]"):
    for st in range(N - 1):
        #print(f"st = {st}")
        ti = 0
        for tr in range(st, N - 1):
            #print(f"ti = {ti}, F[tr] = {F[tr]}")
            if ti < S[tr]:
                ti = S[tr] + C[tr]
            elif ti % F[tr] == 0:
                ti += C[tr]
            else:
                ti += F[tr] - (ti % F[tr]) # 待ち時間
                ti += C[tr]
            #print(f"ti = {ti}")
        print(ti)
    print(0)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    C = [int()] * (N - 1)  # type: "List[int]"
    S = [int()] * (N - 1)  # type: "List[int]"
    F = [int()] * (N - 1)  # type: "List[int]"
    for i in range(N - 1):
        C[i] = int(next(tokens))
        S[i] = int(next(tokens))
        F[i] = int(next(tokens))
    solve(N, C, S, F)

if __name__ == '__main__':
    main()
