#include <bits/stdc++.h>
using namespace std;
using ll = long long;

void solve(long long N, std::vector<long long> A){
  ll tmp = 0;
  for (ll i = 0; i < N; i++) {
    if (i % 2 == 0) {
      tmp += A[i];
    } else {
      tmp -= A[i];
    }
  }
  cout << tmp;
  for (ll i = 1; i < N; i++) {
    tmp = (A[i - 1] - tmp / 2) * 2;
    cout << ' ' << tmp;
  }
  cout << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    std::vector<long long> A(N);
    for(ll i = 0 ; i < N ; i++){
        scanf("%lld",&A[i]);
    }
    solve(N, std::move(A));
    return 0;
}
