#include <bits/stdc++.h>
using namespace std;


void solve(long long N, long long K, std::vector<long long> x){
  long long ans = 100000000000000000;
  long long tmp = 0;
  for (long long i = 0; i < N; i++) {
    if (i + K <= N) {
      if (x[i] * x[i + K - 1] > 0) {
        tmp = max(abs(x[i]), abs(x[i + K - 1]));
      } else {
        tmp = abs(x[i]) + abs(x[i + K - 1]) + min(abs(x[i]), abs(x[i + K - 1]));
      }
      if (tmp < ans) {
        ans = tmp;
      }
    } else {
      break;
    }
  }
  cout << ans << endl;
}

// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
int main(){
    long long N;
    scanf("%lld",&N);
    long long K;
    scanf("%lld",&K);
    std::vector<long long> x(N);
    for(int i = 0 ; i < N ; i++){
        scanf("%lld",&x[i]);
    }
    solve(N, K, std::move(x));
    return 0;
}
