#!/usr/bin/env python3
import sys


def solve(N: int, s: "List[int]"):
    s.sort()
    a_sum = sum(s)
    if a_sum % 10 != 0:
        print(a_sum)
        return
    for i in range(N):
        if s[i] % 10 != 0:
            print(a_sum - s[i])
            return
    print(0)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    s = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, s)

if __name__ == '__main__':
    main()
