#!/usr/bin/env python3

# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    T = int(input())
    N = [int()] * T
    S = [int()] * T
    K = [int()] * T
    for i in range(T):
        N[i], S[i], K[i] = map(int, input().split())

    for i in range(T):
        n, s, k = N[i], S[i], K[i]
        tmp_s = s
        ans = 0
        if n >= k:
            next_s = (n - tmp_s) % k
            ans += (n - tmp_s) // k
            if tmp_s == 0:
                return ans
            tmp_s = n - next_s

if __name__ == '__main__':
    main()
