#!/usr/bin/env python3
import sys


def solve(A: int, B: int, C: int):
    if not (A % 2 == 0 and B % 2 == 0 and C % 2 == 0):
        print(0)
        return

    if A == B and B == C:
        print(-1)
        return

    ans = 0
    while True:
        if not (A % 2 == 0 and B % 2 == 0 and C % 2 == 0):
            print(ans)
            return

        ans += 1
        newA = B / 2 + C / 2
        newB = A / 2 + C / 2
        newC = A / 2 + B / 2

        A = newA
        B = newB
        C = newC

    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    C = int(next(tokens))  # type: int
    solve(A, B, C)

if __name__ == '__main__':
    main()
