#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(N: int, a: "List[int]"):
    li = a
    # 2をいくつ含むか
    a = 0 # 4の倍数
    b = 0 # 2の倍数
    c = 0

    for i in li:
        if i % 4 == 0:
            a += 1
            continue
        if i % 2 == 0:
            b += 1
            continue
        c += 1

    if (c > 0 and b > 0 and c <= a) or \
        (c > 0 and b == 0 and c - 1 <= a) or \
        (c == 0):
        print(YES)
    else:
        print(NO)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, a)

if __name__ == '__main__':
    main()
