#!/usr/bin/env python3
import sys
import math


def solve(H: int, W: int):
    # even or odd for H and W
    if W == 1 or H == 1:
        ans = 1
    elif H % 2 == 0: # even
        ans = int(W * (H / 2))
    else:
        ans = int(W * math.floor(H /2) + math.ceil(W / 2))
    print(ans)
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    solve(H, W)

if __name__ == '__main__':
    main()
