#!/usr/bin/env python3
import sys
import copy


def solve(H: int, W: int, S: "List[str]"):
    ans = [['.'] * W for _ in range(H)]
    for i in range(H):
        for j in range(W):
            if S[i][j] == '.':
                #print(S[max(0, i - 1):i + 2])
                #print([s[max(j - 1, 0):j + 2] for s in S[max(0, i - 1):i + 2]])
                #print([s[max(j - 1, 0):j + 2].count('#') for s in S[max(0, i - 1):i + 2]])
                ans[i][j] = str(sum(s[max(j - 1, 0):j + 2].count('#') for s in S[max(0, i - 1):i + 2]))
            else:
                ans[i][j] = '#'
    for s in ans:
        print("".join(s))
    return


# Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    H = int(next(tokens))  # type: int
    W = int(next(tokens))  # type: int
    S = [next(tokens) for _ in range(H)]  # type: "List[str]"
    solve(H, W, S)

if __name__ == '__main__':
    main()
